# Generated by Django 5.0.7 on 2024-08-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0002_remove_user_email_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='dddd', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='interests',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
