# Generated by Django 5.0.7 on 2024-08-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0003_user_name_alter_user_interests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AlterField(
            model_name='user',
            name='interests',
            field=models.TextField(),
        ),
    ]
